Set up google cloud via vault, run integration tests
Lifted from https://github.com/broadinstitute/gotc-deploy's actions

Assumes four secrets in GitHub:
ROLE_ID
SECRET_ID
VAULT_ADDR
SA_KEY_PATH (the actual .json file within vault of the target
gcloud service account's key)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -42,14 +42,54 @@ jobs:
         with:
           tools-deps: '1.10.1.469'
 
+      # Get secret from vault
+      # Lifted from https://github.com/broadinstitute/gotc-deploy/'s actions
+      - name: Authenticate to Gcloud
+        id: gcloud
+        env:
+          ROLE_ID: ${{ secrets.ROLE_ID }}
+          SECRET_ID: ${{ secrets.SECRET_ID }}
+          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
+          SA_KEY_PATH: ${{ secrets.SA_KEY_PATH }}
+        run: |
+          # get vault token using role-id and secret-id
+          VAULT_TOKEN=$(curl \
+              --request POST \
+              --data "{\"role_id\":\"${ROLE_ID}\",\"secret_id\":\"${SECRET_ID}\"}" \
+              ${VAULT_ADDR}/v1/auth/approle/login | jq -r .auth.client_token)
+          if [ -z "${VAULT_TOKEN}" ] ; then
+             echo "Vault authentication failed!"
+             exit 1
+          fi
+          echo ::add-mask::${VAULT_TOKEN}
+          echo ::set-env name=VAULT_TOKEN::${VAULT_TOKEN}
+          # use vault token to read secret - service account json
+          curl --silent -H "X-Vault-Token: ${VAULT_TOKEN}" -X GET \
+               ${VAULT_ADDR}${SA_KEY_PATH} \
+               | jq .data > sa.json
+          if [ ! -s sa.json ] ; then
+             echo "Retrieval of Gcloud SA credentials failed"
+             exit 1
+          fi
+          # auth as service account
+          gcloud auth activate-service-account --key-file=sa.json
+          if [ $? -ne 0 ] ; then
+             echo "Gcloud auth failed!"
+             exit 1
+          fi
+
+
       - name: lint
         run: clojure -A:lint
 
       - name: build
         run: clojure -A:build
 
-      - name: test
+      - name: unit test
         run: clojure -A:test unit
+
+      - name: integration test
+        run: clojure -A:test integration
 
       - name: package
         run: |
